### ISSUE TITLE
Feat: Socials footer component

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/next-grapql-rick-and-morty#13]
# Task Title

Task: Create a footer with all socials link

## Task Description

This Task will add a reusable footer on all pages

Tasks:

- [ ] Create a footer layout,(responsive)
- [ ] Add icons for LinkedIn, Twitter, Github
- [ ] Add links for all above icons
- [ ] Add created with vercel badge
- [ ] Add copyright tag
