### ISSUE TITLE
Feat: Character Poster

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/next-grapql-rick-and-morty#2]
# Character Poster

Task: Create Character Poster

## Task Description

This Task will complete character poster component, which will be shown on character listing page

## Epic Parent

- [x] Create a character poster layout
- [x] Added props with following values (name, image)
- [x] Add hover effect
- [x] Add link to poster which will redirect to the detailed character page
