### ISSUE TITLE
Feat: Chracter details page

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/next-grapql-rick-and-morty#3]
# Task Title
Character Details

## Task description
Create a character details page and add it to the character listing page

## Tasks

- [x] Create character details card layout
- [x] Add types for card
- [x] Fetch id from next query
- [x] Create graphql query for finding character by id
- [x] Fetch character info from useQuery
- [x] Add back to characters button
