### ISSUE TITLE
Feat: Header & Container component

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/next-grapql-rick-and-morty#4]
# Task Title

Task: Header & Container component

## Task Description

This Task will add a header component 

#### Header
- [x] Create header layout
- [x] Add 3 links in the header
- [x] Add dynamic styles for the active routes

#### Container
- [x] Create a container component that will wrap around all the other components
- [x] Make container responsive
