### ISSUE TITLE
Feat: Searchbar component

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/next-grapql-rick-and-morty#5]
# Task Title

Task: Searchbar component

## Task Description

This Task will add a search bar component to the character listing page

### Tasks

- [ ] Create a search bar layout
- [ ] Add input field for search
- [ ] Set query for searching characters
- [ ] Send query from searchBar to character listing page
