### ISSUE TITLE
Feat: Pagination

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/next-grapql-rick-and-morty#6]
# Task Title

Task: Pagination component

## Task Description

This Task will add a pagination component to the character listing page

### Tasks

- [x] Create pagination layout
- [x] Fetch the character count  and set pages
- [x] Show buttons for all pages
- [x] Add previous and next pages
