### ISSUE TITLE
Feat: Compose cmoponents in character listing

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/next-grapql-rick-and-morty#7]
# Task Title

Task: Compose all components in character listing page

## Task Description

This Task will compose all components in character listing page

## Epic Parent

Tasks:

- [ ] Add all components in the page
- [ ] Set up the states for page and search query
- [ ] Add graphql query for filtering character by name and page
- [ ] User query with apollo query
